app/asset/forms.py
# coding:utf-8

from flask_wtf import FlaskForm
from wtforms import SelectField, StringField, TextAreaField, SubmitField, \
    PasswordField, SelectMultipleField
from wtforms.validators import DataRequired, Length, Email, EqualTo



class QueryForm(FlaskForm):
    env = SelectField(u'全部环境', coerce=str)
    used = SelectField(u'是否使用', coerce=str)
    verify = SelectField(u'password', coerce=str)
    ip = StringField(u'ip')


class EditHostInfoForm(QueryForm):
    username = StringField(u'用户名', validators=[DataRequired()])
    password = StringField(u'密码', validators=[DataRequired()])
    hostname = StringField(u'HOSTNAME', validators=[DataRequired()])

app/asset/__init__.py
from flask import Blueprint


asset = Blueprint('asset', __name__)


from . import views

app/asset/views.py
# coding:utf-8
import sys
reload(sys)
sys.setdefaultencoding('utf-8')

from flask import render_template, request, redirect, url_for, flash, jsonify
from . import asset
from ..models import All_hosts, Status, Cmdb_env
from .forms import QueryForm, EditHostInfoForm
from flask_login import login_required
from .. import db
from flask import json


@asset.route('/manage_hosts', methods=['GET', 'POST'])
@login_required
def manage_hosts():
    env_id = request.args.get('env_id', -1, type=str)
    used_id = request.args.get('used_id', -1, type=str)
    password_id = request.args.get('password_id', -1, type=str)
    ip = request.args.get('ip', '', type=str)

    form = QueryForm(request.form, env=env_id, used=used_id, password_id=password_id, ip=ip)
    form2 = EditHostInfoForm()

    envs = [(s.env, s.env) for s in Cmdb_env.query.all()]
    envs.append(("-1", u'全部环境'))

    use_status = [("-1", u'IP状态'), ('Y', u'IP已使用'), ('N', u'IP未占用')]

    password_verify = [("-1", u'密码状态'), ('error', u'错误'), ('correct', u'正确')]

    form.env.choices = envs
    form.used.choices = use_status
    form.verify.choices = password_verify
    pagination_search = 0

    if form.validate_on_submit() or \
            (request.args.get('password_id') is not None and request.args.get('used_id') is not None and request.args.get('env_id') is not None):
        if form.validate_on_submit():
            env_id = form.env.data
            used_id = form.used.data
            password_id = form.verify.data
            ip = form.ip.data
            page = 1
        else:
            env_id = request.args.get('env_id')
            used_id = request.args.get('used_id')
            password_id = request.args.get('password_id')
            form.env.data = env_id
            form.used.data = used_id
            form.verify.data = password_id
            ip = form.ip.data
            page = request.args.get('page', 1, type=int)

        hosts_list = All_hosts.query.order_by(All_hosts.ip)

        if env_id != "-1" and env_id is not None:
            hosts_list = hosts_list.filter_by(env=env_id)
        if used_id != "-1" and used_id is not None:
            hosts_list = hosts_list.filter_by(is_used=used_id)
        if password_id != "-1" and password_id is not None:
            hosts_list = hosts_list.filter_by(passwd_result=password_id)
        if ip != '' and ip is not None:
            ipp = "%" + ip + "%"
            #hosts_list = hosts_list.filter(All_hosts.ip.like(ipp))

            hosts_list = hosts_list.filter(All_hosts.ip.like(ipp) | All_hosts.hostname.like(ipp))

        pagination_search = hosts_list.paginate(page, per_page=20, error_out=False)
    if pagination_search != 0:
        pagination = pagination_search
        hosts_list = pagination_search.items
    else:
        page = request.args.get('page', 1, type=int)
        pagination = All_hosts.query.order_by(All_hosts.ip).paginate(
                page, per_page=20,
                error_out=True)
        hosts_list = pagination.items

    return render_template('asset/all_cu_lists.html', page=page, hosts_list=hosts_list, env_id=env_id, used_id=used_id, password_id=password_id, ip=ip, form=form, form2=form2, pagination=pagination)


@asset.route('/manage-hosts/get-host-info/<int:id>', methods=['GET', 'POST'])
@login_required
def get_host_info(id):
    print type(id)
    if request.is_xhr:
        host_info = All_hosts.query.get_or_404(id)
        return jsonify({
            'hostname': host_info.hostname,
            'ip': host_info.ip,
            'username': host_info.username,
            'password': host_info.password
        })


@asset.route('/manage_hosts/edit-host-info', methods=['GET', 'POST'])
@login_required
def edit_host_info():
    form2 = EditHostInfoForm()
    ip = form2.ip.data
    username = form2.username.data
    password = form2.password.data
    hostname = form2.hostname.data

    host = All_hosts.query.filter_by(ip=ip).first()

    host.username = username
    host.password = password
    host.hostname = hostname
    db.session.commit()
    flash(u'修改host信息成功！', 'success')
    return redirect(url_for('asset.manage_hosts'))

app/templates/asset/all_cu_lists.html
{% extends 'base.html' %}
{% from '_pagination.html' import pagination_widget %}



{% block admin_content %}
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>Hosts Management</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="{{ url_for('admin.index') }}">Dashbord</a>
                </li>
                <li class="active">
                    <strong>All Hosts</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-2">

        </div>
    </div>

    <div class="wrapper wrapper-content animated fadeInRight" style="margin: -10px -10px">
        <div class="row">
            <div class="col-sm-12">
                <div class="ibox float-e-margins" id="all">
                    <div class="ibox-title">
                        <h5> 主机详细信息列表</h5>
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                            <a class="close-link">
                                <i class="fa fa-times"></i>
                            </a>
                        </div>
                    </div>

                    <div class="ibox-content">
                        <form class="form-inline" method="post" action="">
                            {{ form.hidden_tag() }}

                            <div class="col-sm-8" style="padding-left: 0px">
                                <label>
                                    {{ form.env(class='form-control m-b input-sm', required='', id='env_id') }}
                                </label>

                                <label>
                                    {{ form.used(class='form-control m-b input-sm', required='', id='used_id') }}
                                </label>

                                <label>
                                    {{ form.verify(class='form-control m-b input-sm', required='', id='password_id') }}
                                </label>

                            </div>

                            <div class="col-sm-4" style="padding-right: 0px">
                                 <div class="input-group inline-group" style="float: right; padding-right: 0px">
                                        {{ form.ip(class='form-control m-b input-sm', placeholder='Please enter ip or hostname', id='ip') }}
                                    <div class="input-group-btn">
                                        <button id="search_btn"  type="submit" class="btn btn-sm btn-primary search-btn">
                                            - 搜索 -
                                        </button>
                                    </div>
                                </div>
                            </div>



                            <table class="table table-striped table-bordered table-hover " id="editable" name="editable">
                                <thead>
                                    <tr>
                                        <th class="text-center">所属环境</th>
                                        <th class="text-center">HOSTNAME</th>
                                        <th class="text-center">IP</th>
                                        <th class="text-center">USERNAME</th>
                                        <th class="text-center">PASSWORD</th>
                                        <th class="text-center">是否使用</th>
                                        <th class="text-center">System version</th>
                                        <th class="text-center">密码是否正确</th>
                                        <th class="text-center">操作</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for host in hosts_list %}
                                    <tr>
                                        <td class="text-center">{{host.env}}</td>
                                        <td class="text-center">{{host.hostname}}</td>
                                        <td class="text-center">{{host.ip}}</td>
                                        <td class="text-center">{{host.username}}</td>
                                        <td class="text-center">{{host.password}}</td>
                                        <td class="text-center">{{host.is_used}}</td>
                                        <td class="text-center">{{host.systeminfo}}</td>
                                        <td class="text-center">{{host.passwd_result}}</td>
                                        <td class="text-center">
                                             <a class="btn btn-xs btn-info" title="edit host"
                                               onclick="EditHostInfo('{{ url_for('asset.get_host_info', id=host.id) }}')">编辑
                                            </a>
                                        </td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                            <div class="row">
                                <div class="col-sm-6" style="float: right;margin-top: 0">
                                    <ul class="pagination" style="float: right;margin-top: -20px;margin-bottom: -20px">
                                        {{ pagination_widget(pagination, 'asset.manage_hosts', env_id=env_id, used_id=used_id, password_id=password_id, ip=ip) }}
                                    </ul>
                                </div>
                            </div>


                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>





<!-- 信息修改确认: For edit host -->
<div class="modal fade" id="editHostInfoFormModal">
    <div class="modal-dialog">
        <div class="modal-content message_align">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">×</span></button>
                <h4 class="modal-title" id="ModalTitle"></h4>
            </div>
            <form id="editArticleTypeForm" method="post"
                  action="{{ url_for('asset.edit_host_info') }}">
                <div class="modal-body">
                        <div class="form-group">
                            {{ form2.hostname.label }}
                            {{ form2.hostname(id='edithostname', class='form-control') }}
                            {{ form2.ip.label }}
                            {{ form2.ip(id='editip', class='form-control', required='') }}
                            {{ form2.username.label }}
                            {{ form2.username(id='editusername', class='form-control') }}
                            {{ form2.password.label }}
                            {{ form2.password(id='editpassword', class='form-control') }}

                        </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                    <button id="editHostCfmClick" type="submit" class="btn btn-success">确定</button>
                </div>
            </form>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->




{% endblock %}