app/config/forms.py
# coding:utf-8

from flask_wtf import FlaskForm
from wtforms import SelectField, StringField, TextAreaField, SubmitField, \
    PasswordField, SelectMultipleField, FieldList
from wtforms.validators import DataRequired, Length, Email, EqualTo




class AddEnvForm(FlaskForm):
    envs = StringField(u'环境', validators=[DataRequired()])
    description = TextAreaField(u'环境说明')


class AddEnvItermForm(AddEnvForm):
    env_iterm_template = SelectField(u'配置项模板', validators=[DataRequired()])


class AddSubSystemForm(FlaskForm):
    systems = StringField(u'子系统', validators=[DataRequired()])
    description = TextAreaField(u'环境说明')


class AddFileForm(FlaskForm):
    conf_file = StringField(u'文件名', validators=[DataRequired()])
    description = TextAreaField(u'环境说明')


class AddKeyForm(FlaskForm):
    systems = SelectField(u'子系统', validators=[DataRequired()])
    files = SelectField(u'文件名', validators=[DataRequired()])
    keys = TextAreaField(u'key', validators=[DataRequired()])
    branch_name = StringField(u'branch_name', validators=[DataRequired()])
    jira_id = StringField(u'jira_id', validators=[DataRequired()])
    description = TextAreaField(u'配置项说明')


class QueryKeyForm(FlaskForm):
    systems = SelectField(u'子系统')
    files = SelectField(u'文件名')
    keys = StringField(u'keys')



class CheckKeyForm(FlaskForm):
    systems = SelectField(u'子系统', validators=[DataRequired()])
    path = TextAreaField(u'路径', validators=[DataRequired()])


class AddKeyValueForm(FlaskForm):
    envs = SelectField(u'环境', validators=[DataRequired()])
    systems = SelectField(u'子系统', validators=[DataRequired()])
    files = SelectField(u'文件名', validators=[DataRequired()])
    keys = TextAreaField(u'key', validators=[DataRequired()])
    values = TextAreaField(u'value', validators=[DataRequired()])
    jira_id = StringField(u'jira_id')
    branch_name = StringField(u'branch_name')
    description = TextAreaField(u'配置项说明')


class EditKeyValueForm(FlaskForm):
    envs = SelectField(u'环境', validators=[DataRequired()])
    systems = SelectField(u'子系统')
    files = SelectField(u'文件名')
    keys = TextAreaField(u'key')
    values = TextAreaField(u'value', validators=[DataRequired()])
    version = StringField(u'version')
    description = TextAreaField(u'配置项说明')


class BatchAddKeyValueForm(FlaskForm):
    systems = SelectField(u'子系统', validators=[DataRequired()])
    files = SelectField(u'文件名', validators=[DataRequired()])
    keys = TextAreaField(u'key', validators=[DataRequired()])
    jira_id = StringField(u'jira_id')
    branch_name = StringField(u'branch_name', validators=[DataRequired()])
    description = TextAreaField(u'环境说明')


class BatchEditKeyValueForm(FlaskForm):
    systems = SelectField(u'子系统', validators=[DataRequired()])
    files = SelectField(u'文件名', validators=[DataRequired()])
    keys = TextAreaField(u'key', validators=[DataRequired()])
    version = StringField(u'version', validators=[DataRequired()])
    description = TextAreaField(u'环境说明')


class QueryKeyValueForm(FlaskForm):
    envs = SelectField(u'环境')
    systems = SelectField(u'子系统')
    files = SelectField(u'文件名')
    keys = StringField(u'keys')


class QueryFileForm(FlaskForm):
    conf_file = StringField(u'文件名')


class QueryVersionForm(FlaskForm):
    envs = SelectField(u'环境')
    versions = StringField(u'versions')

class AddVersionForm(FlaskForm):
    envs = SelectField(u'环境', validators=[DataRequired()])
    git_branchs = TextAreaField(u'配置项说明')
    description = TextAreaField(u'配置项说明')

app/config/__init__.py
from flask import Blueprint


config = Blueprint('config', __name__)


from . import views

app/config/views.py
# coding:utf-8
import sys
reload(sys)
sys.setdefaultencoding('utf-8')

from flask import render_template, request, redirect, url_for, flash, jsonify
from . import config
from ..models import Cmdb_env, Cmdb_conf_file, Cmdb_other_config, Conf_key_value1, Cmdb_system, Cmdb_conf_key, Cmdb_conf_key_value, Cmdb_conf_version, Cmdb_conf_special_key, Cmdb_conf_special_key_value
from .forms import AddEnvForm, AddFileForm, AddKeyValueForm, QueryKeyValueForm, QueryFileForm, AddEnvItermForm, \
    BatchAddKeyValueForm, AddSubSystemForm, CheckKeyForm, AddKeyForm, QueryKeyForm, QueryVersionForm, EditKeyValueForm,\
    AddVersionForm
from flask_login import login_required
from .. import db
import fileinput
import shutil
import os, time, re
import requests
from sqlalchemy import func
import get_tree_json
from sqlalchemy import or_

'''
环境列表
'''

@config.route('/env', methods=['GET', 'POST'])
@login_required
def env():
    env_lists = Cmdb_env.query.order_by(Cmdb_env.id)

    return render_template('config/env_list.html', env_lists=env_lists)


'''
环境新增
'''

@config.route('/env_add', methods=['GET', 'POST'])
@login_required
def env_add():
    form = AddEnvForm()
    if form.validate_on_submit():
        env = form.envs.data
        description = form.description.data
        env_info = Cmdb_env.query.filter_by(env=env).first()
        if env_info:
            flash(u'添加环境失败,该环境已存在。', 'danger')
        else:
            env = Cmdb_env(env=env, description=description)
            db.session.add(env)
            db.session.commit()
            return redirect(url_for('config.env'))

    return render_template('config/env_add.html', form=form)


'''
环境配置项新增
'''

@config.route('/env_iterm_add', methods=['GET', 'POST'])
@login_required
def env_iterm_add():
    form = AddEnvItermForm()
    envs = [(t.env, t.env) for t in Cmdb_env.query.all()]
    form.env_iterm_template.choices = envs
    if form.validate_on_submit():
        new_env = form.envs.data
        env_iterm = form.env_iterm_template.data
        description = form.description.data
        env = Cmdb_env(env=new_env, description=description)
        db.session.add(env)
        db.session.commit()

        print type(new_env), new_env
        print type(env_iterm), env_iterm

        add_iterm_sql = "INSERT into `conf_iterm`(`conf_env`, `conf_file`, `original_value`, `replace_value`, `description`, `status`) SELECT" + " '" + new_env + "'" + ", `conf_file`, `original_value`, '', `description`, `status` FROM `conf_iterm` WHERE `conf_env`=" + "'" + env_iterm + "'" + ";"

        db.session.execute(add_iterm_sql)
        db.session.commit()

        print add_iterm_sql

        return redirect(url_for('config.env'))
    return render_template('config/env_iterm_add.html', form=form)



'''
环境删除
'''

@config.route('/env_del', methods=['GET', 'POST'])
@login_required
def env_del():
    id_json = request.get_json()
    id = id_json['data']
    env = Cmdb_env.query.get_or_404(id)
    db.session.delete(env)
    db.session.commit()

'''
环境修改
'''

@config.route('/env_edit', methods=['GET', 'POST'])
@login_required
def env_edit():
    env_id = request.args.get('env_id')
    #print type(env_id)
    env = Cmdb_env.query.get_or_404(env_id)
    form = AddEnvForm()

    if form.validate_on_submit():
        form = AddEnvForm()
        conf_env = form.envs.data
        env_info = Cmdb_env.query.filter_by(env=conf_env).first()

        if env_info and str(env_info.id) != str(env_id):
            flash(u'修改环境失败,该环境已存在。', 'danger')
        else:
            db.session.query(Cmdb_env).filter_by(id=env_id).update({"env": form.envs.data, "description": form.description.data})
            db.session.commit()
            return redirect(url_for('config.env'))


    form.envs.data = env.env
    form.description.data = env.description

    return render_template('config/env_edit.html', form=form)



'''############################################################################################################################################'''
'''############################################################################################################################################'''
'''############################################################################################################################################'''




'''
子系统列表
'''

@config.route('/sub_system', methods=['GET', 'POST'])
@login_required
def sub_system():
    sub_system_lists = Cmdb_system.query.filter_by(flag="1").order_by(Cmdb_system.id)

    return render_template('config/sub_system_list.html', sub_system_lists=sub_system_lists)


'''
子系统新增
'''

@config.route('/sub_system_add', methods=['GET', 'POST'])
@login_required
def sub_system_add():
    form = AddSubSystemForm()
    if form.validate_on_submit():
        sub_system = form.systems.data
        description = form.description.data

        sub_system_info = Cmdb_system.query.filter_by(name=sub_system).first()
        if sub_system_info:
            flash(u'添加子系统失败,该子系统已存在。', 'danger')
        else:
            sub_system = Cmdb_system(name=sub_system, description=description, flag="1")
            db.session.add(sub_system)
            db.session.commit()

            return redirect(url_for('config.sub_system'))

    return render_template('config/sub_system_add.html', form=form)


'''
子系统删除
'''

@config.route('/sub_system_del', methods=['GET', 'POST'])
@login_required
def sub_system_del():
    id_json = request.get_json()
    id = id_json['data']
    sub_system = Cmdb_system.query.get_or_404(id)
    db.session.delete(sub_system)
    db.session.commit()


'''
子系统修改
'''

@config.route('/sub_system_edit', methods=['GET', 'POST'])
@login_required
def sub_system_edit():
    sub_system_id = request.args.get('sub_system_id')
    sub_system = Cmdb_system.query.get_or_404(sub_system_id)
    print sub_system
    form = AddSubSystemForm()

    if form.validate_on_submit():
        form = AddSubSystemForm()

        name = form.systems.data
        description = form.description.data

        #print sub_system

        sub_system_info = Cmdb_system.query.filter_by(name=name).first()
        print sub_system_info

        if sub_system_info and str(sub_system_info.id) != str(sub_system_id):
            flash(u'修改子系统失败,%s子系统已存在。' % name, 'danger')
        else:
            db.session.query(Cmdb_system).filter_by(id=sub_system_id).update({"name": name, "description": description})
            db.session.commit()
            return redirect(url_for('config.sub_system'))


    form.systems.data = sub_system.name
    form.description.data = sub_system.description

    return render_template('config/sub_system_edit.html', form=form)



'''############################################################################################################################################'''
'''############################################################################################################################################'''
'''############################################################################################################################################'''



'''
配置文件列表
'''

@config.route('/conf_file', methods=['GET', 'POST'])
@login_required
def conf_file():
    conf_file = request.args.get('conf_file', '', type=str)
    form = QueryFileForm(request.form, conf_file=conf_file)
    file_lists = Cmdb_conf_file.query.order_by(Cmdb_conf_file.id)

    pagination_search = 0

    if form.validate_on_submit():
        conf_file = form.conf_file.data
        page = 1
    else:
        conf_file = form.conf_file.data
        page = request.args.get('page', 1, type=int)

    file_lists = Cmdb_conf_file.query.order_by(Cmdb_conf_file.id)


    if conf_file != '' and conf_file is not None:
        conf_file_like = "%" + conf_file + "%"
        file_lists = file_lists.filter(Cmdb_conf_file.conf_file.like(conf_file_like))

    pagination_search = file_lists.paginate(page, per_page=15, error_out=False)

    if pagination_search != 0:
        pagination = pagination_search
        file_lists = pagination_search.items
    else:
        page = request.args.get('page', 1, type=int)
        pagination = Cmdb_conf_file.query.order_by(Cmdb_conf_file.id).paginate(
                page, per_page=15,
                error_out=True)
        file_lists = pagination.items


    return render_template('config/file_list.html', page=page, file_lists=file_lists, conf_file=conf_file, pagination=pagination, form=form)


'''
配置文件新增
'''

@config.route('/file_add', methods=['GET', 'POST'])
@login_required
def file_add():
    form = AddFileForm()

    if form.validate_on_submit():
        conf_file = form.conf_file.data
        description = form.description.data

        file_info = Cmdb_conf_file.query.filter_by(conf_file=conf_file).first()
        if file_info:
            flash(u'添加文件失败,该文件已存在。', 'danger')
        else:
            file = Cmdb_conf_file(conf_file=conf_file,
                           description=description,
                             )
            db.session.add(file)
            db.session.commit()
            return redirect(url_for('config.conf_file'))

    return render_template('config/file_add.html', form=form)


'''
配置文件删除
'''

@config.route('/file_del', methods=['GET', 'POST'])
@login_required
def file_del():
    id_json = request.get_json()
    id = id_json['data']
    file = Cmdb_conf_file.query.get_or_404(id)
    db.session.delete(file)
    db.session.commit()


'''
配置文件修改
'''

@config.route('/file_edit', methods=['GET', 'POST'])
@login_required
def file_edit():
    file_id = request.args.get('file_id')
    file = Cmdb_conf_file.query.get_or_404(file_id)
    form = AddFileForm()

    if form.validate_on_submit():
        conf_file = form.conf_file.data
        description = form.description.data

        file_info = Cmdb_conf_file.query.filter_by(conf_file=conf_file).first()

        if file_info and str(file_info.id) != str(file_id):

app/templates/config/env_add.html
{% extends 'base.html' %}




{% block title_content %}
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>环境管理</h2>
        <ol class="breadcrumb">
            <li>
                <a href="{{ url_for('admin.index') }}">Dashbord</a>
            </li>
            <li>
                <a>配置管理</a>
            </li>
            <li class="active">
                <strong>新增环境</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>
{% endblock %}

{% block admin_content %}
    <div id="ibox-content" class="ibox-title">
        <h5> 填写环境基本信息 </h5>
        <div class="ibox-tools">
            <a class="collapse-link">
                <i class="fa fa-chevron-up"></i>
            </a>
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <i class="fa fa-wrench"></i>
            </a>
            <a class="close-link">
                <i class="fa fa-times"></i>
            </a>
        </div>
    </div>

    <div class="ibox-content">
        <div class="panel blank-panel">
            <div class="panel-options">
                <ul class="nav nav-tabs">
                    <li class="active"><a href="{{ url_for('config.env_add') }}" class="text-center"><i class="fa fa-laptop"></i> 单独添加环境 </a></li>
                    <li><a href="{{ url_for('config.env_iterm_add') }}" class="text-center"><i class="fa fa-bar-chart-o"></i> 同时添加配置项 </a></li>
                </ul>
                </ul>
            </div>
            <div class="panel-body">
                <div class="tab-content">
                        <form class="form-horizontal" role="form" method="POST" action="{{ url_for('config.env_add') }}">
                        {{ form.hidden_tag() }}
                        <div class="form-group">
                            <label class="col-sm-2 control-label">环境</label>
                            <div class="col-sm-10">
                                {{ form.envs(class='form-control', placeholder='envs', required='') }}
                            </div>
                        </div>

                        <div class="hr-line-dashed"></div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label">环境简介</label>
                            <div class="col-sm-10">
                                {{ form.description(class='form-control', placeholder='description', required='') }}
                            </div>
                        </div>

                        <div class="hr-line-dashed"></div>


                        <div class="form-group">
                            <div class="col-sm-4 col-sm-offset-2">
                                <button class="btn btn-primary" type="submit"> 提交 </button>
                            </div>
                        </div>

                        </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

app/templates/config/env_iterm_add.html
{% extends 'base.html' %}



{% block title_content %}
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Environmental management</h2>
        <ol class="breadcrumb">
            <li>
                <a href="{{ url_for('admin.index') }}">Dashbord</a>
            </li>
            <li>
                <a>Configuration management</a>
            </li>
            <li class="active">
                <strong>Add Environmental</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>
{% endblock %}

{% block admin_content %}

    <div id="ibox-content" class="ibox-title">
        <h5> 填写资产基本信息 </h5>
        <div class="ibox-tools">
            <a class="collapse-link">
                <i class="fa fa-chevron-up"></i>
            </a>
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <i class="fa fa-wrench"></i>
            </a>
            <a class="close-link">
                <i class="fa fa-times"></i>
            </a>
        </div>
    </div>

    <div class="ibox-content">
        <div class="panel blank-panel">
            <div class="panel-options">
                <ul class="nav nav-tabs">
                    <li><a href="{{ url_for('config.env_add') }}" class="text-center"><i class="fa fa-laptop"></i> 单独添加环境 </a></li>
                    <li class="active"><a href="{{ url_for('config.env_iterm_add') }}" class="text-center"><i class="fa fa-bar-chart-o"></i> 同时添加配置项 </a></li>
                </ul>
            </div>
            <div class="panel-body">
                <div class="tab-content">
                        <form class="form-horizontal" role="form" method="POST" action="{{ url_for('config.env_iterm_add') }}">
                        {{ form.hidden_tag() }}
                        <div class="form-group">
                            <label class="col-sm-2 control-label">环境</label>
                            <div class="col-sm-10">
                                {{ form.envs(class='form-control', placeholder='Envs', required='') }}
                            </div>
                        </div>

                        <div class="hr-line-dashed"></div>


                        <div class="form-group">
                            <label class="col-sm-2 control-label">配置项参照环境</label>
                            <div class="col-sm-10">
                                {{ form.env_iterm_template(class='form-control', placeholder='Configuration item reference', required='') }}
                            </div>
                        </div>

                        <div class="hr-line-dashed"></div>


                        <div class="form-group">
                            <label class="col-sm-2 control-label">环境简介</label>
                            <div class="col-sm-10">
                                {{ form.description(class='form-control', placeholder='Description', required='') }}
                            </div>
                        </div>

                        <div class="hr-line-dashed"></div>


                        <div class="form-group">
                            <div class="col-sm-4 col-sm-offset-2">
                                <button class="btn btn-primary" type="submit"> 提交 </button>
                            </div>
                        </div>

                        </form>
                </div>
            </div>
        </div>
    </div>



{% endblock %}

app/templates/config/file_add.html
{% extends 'base.html' %}




{% block title_content %}
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>配置文件管理</h2>
        <ol class="breadcrumb">
            <li>
                <a href="{{ url_for('admin.index') }}">Dashbord</a>
            </li>
            <li>
                <a>配置管理</a>
            </li>
            <li class="active">
                <strong>修改配置文件</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>
{% endblock %}

{% block admin_content %}

    <div id="ibox-content" class="ibox-title">
        <h5> 填写配置文件基本信息 </h5>
        <div class="ibox-tools">
            <a class="collapse-link">
                <i class="fa fa-chevron-up"></i>
            </a>
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <i class="fa fa-wrench"></i>
            </a>
            <a class="close-link">
                <i class="fa fa-times"></i>
            </a>
        </div>
    </div>

    <div class="ibox-content">
        <div class="panel blank-panel">
            <div class="panel-options">
                <ul class="nav nav-tabs">
                    <li class="active"><a class="text-center"><i class="fa fa-laptop"></i> 新增文件 </a></li>
                </ul>
            </div>
            <div class="panel-body">
                <div class="tab-content">
                        <form class="form-horizontal" role="form" method="POST" action="{{ url_for('config.file_add') }}">
                        {{ form.hidden_tag() }}


                        <div class="hr-line-dashed"></div>


                        <div class="form-group">
                            <label class="col-sm-2 control-label">配置文件名</label>
                            <div class="col-sm-10">
                                {{ form.conf_file(class='form-control', placeholder='Config Name', required='') }}
                            </div>
                        </div>

                        <div class="hr-line-dashed"></div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label">配置文件说明</label>
                            <div class="col-sm-10">
                                {{ form.description(class='form-control', placeholder='Config description') }}
                            </div>
                        </div>


                        <div class="hr-line-dashed"></div>

                        <div class="form-group">
                            <div class="col-sm-4 col-sm-offset-2">
                                <button class="btn btn-primary" type="submit"> 提交 </button>
                            </div>
                        </div>

                        </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}


{% block script %}
    {{ super() }}

    <script>
        $(document).ready(function() {
            $(".select_env").select2();

        });

    </script>


{% endblock %}

app/templates/config/init_config.html
{% extends 'base.html' %}



{% block admin_content %}

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>配置项管理</h2>
        <ol class="breadcrumb">
            <li>
                <a href="{{ url_for('admin.index') }}">Dashbord</a>
            </li>
            <li>
                <a>配置管理</a>
            </li>
            <li class="active">
                <strong>配置项检查</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-sm-10">
{#            {% for message in get_flashed_messages() %}#}
{#                <div class="alert alert-warning alert-dismissable" role="alert">#}
{#                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">#}
{#                        &times;#}
{#                    </button>#}
{#                    {{ message }}#}
{#                </div>#}
{#            {% endfor %}#}

            {% for category, message in get_flashed_messages(with_categories=true) %}
                <div class="alert alert-{{ category }} alert-dismissable">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                    {{ message }}
                </div>
            {% endfor %}

            <div class="ibox float-e-margins">
                <div id="ibox-content" class="ibox-title">
                    <h5> 填写配置项信息 </h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <i class="fa fa-wrench"></i>
                        </a>
                        <a class="close-link">
                            <i class="fa fa-times"></i>
                        </a>
                    </div>
                </div>

                <div class="ibox-content">
                    <div class="panel blank-panel">
                        <div class="panel-options">
                            <ul class="nav nav-tabs">
                                <li class="active"><a class="text-center"><i class="fa fa-laptop"></i> 初始化配置 </a></li>
                            </ul>
                        </div>
                        <div class="panel-body">
                            <div class="tab-content">
                                    <form class="form-horizontal" role="form" method="POST" action="">
                                    {{ form.hidden_tag() }}


                                    <div class="hr-line-dashed"></div>


                                    <div class="form-group">
                                        <label class="col-sm-2 control-label">子系统</label>
                                        <div class="col-sm-10">
                                            {{ form.systems(class='form-control select_env', placeholder='Select sub system', required='') }}
                                        </div>
                                    </div>



                                    <div class="hr-line-dashed"></div>


                                    <div class="form-group">
                                        <label class="col-sm-2 control-label">git 分支</label>
                                        <div class="col-sm-10">
                                            {{ form.path(class='form-control', placeholder='git conf path ', required='') }}
                                        </div>
                                    </div>


                                    <div class="hr-line-dashed"></div>

                                    <div class="form-group">
                                        <div class="col-sm-4 col-sm-offset-2">
                                            <button class="btn btn-primary" type="submit"> 提交 </button>
                                        </div>
                                    </div>

                                    </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}


{% block script %}
    {{ super() }}

    <script>
        $(document).ready(function() {
            $(".select_env").select2();

        });

    </script>


{% endblock %}

app/templates/config/sub_system_add.html
{% extends 'base.html' %}



{% block title_content %}

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>子系统管理</h2>
        <ol class="breadcrumb">
            <li>
                <a href="{{ url_for('admin.index') }}">Dashbord</a>
            </li>
            <li>
                <a>配置管理</a>
            </li>
            <li class="active">
                <strong>新增子系统</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>

{% endblock %}

{% block admin_content %}
    <div id="ibox-content" class="ibox-title">
        <h5> 填写子系统信息 </h5>
        <div class="ibox-tools">
            <a class="collapse-link">
                <i class="fa fa-chevron-up"></i>
            </a>
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <i class="fa fa-wrench"></i>
            </a>
            <a class="close-link">
                <i class="fa fa-times"></i>
            </a>
        </div>
    </div>

    <div class="ibox-content">
        <div class="panel blank-panel">
            <div class="panel-options">
                <ul class="nav nav-tabs">
                    <li class="active"><a class="text-center"><i class="fa fa-laptop"></i> 新增子系统 </a></li>
                </ul>
            </div>
            <div class="panel-body">
                <div class="tab-content">
                        <form class="form-horizontal" role="form" method="POST" action="{{ url_for('config.sub_system_add') }}">
                        {{ form.hidden_tag() }}
                        <div class="form-group">
                            <label class="col-sm-2 control-label">子系统</label>
                            <div class="col-sm-10">
                                {{ form.systems(class='form-control', placeholder='sub system', required='') }}
                            </div>
                        </div>

                        <div class="hr-line-dashed"></div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label">子系统简介</label>
                            <div class="col-sm-10">
                                {{ form.description(class='form-control', placeholder='description') }}
                            </div>
                        </div>

                        <div class="hr-line-dashed"></div>


                        <div class="form-group">
                            <div class="col-sm-4 col-sm-offset-2">
                                <button class="btn btn-primary" type="submit"> 提交 </button>
                            </div>
                        </div>

                        </form>
                </div>
            </div>
        </div>
    </div>


{% endblock %}